---
title: TYSM
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  post:
    title: post
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: article
    sharing: false
    license: false
    aside:
      toc: true
    show_edit_on_github: false
    show_subscribe: false
    pageview: true
text_skin: default
highlight_theme: default
url: 
baseurl: 
description: 'Your Site Description

'
lang: 
author:
  type: 
  name: Redacción TYSM
  url: 
  avatar: 
  bio: I am an amazing person.
  email: 
  facebook: 
  twitter: 
  weibo: 
  googleplus: 
  telegram: 
  medium: 
  zhihu: 
  douban: 
  linkedin: 
  github: 
  npm: 
repository: user_name/repo_name
repository_tree: master
paths:
  root: 
  home: 
  archive: 
  rss: 
excerpt_separator: "<!--more-->"
license: CC-BY-NC-4.0
toc:
  selectors: 
mathjax: 
mathjax_autoNumber: 
mermaid: 
chart: 
paginate: 5
paginate_path: "/page:num"
sources: 
sharing:
  provider: addthis
  addthis:
    id: ra-616ede89688c7e87
comments:
  provider: disqus
  disqus:
    shortname: blog-mko160ea9f
  gitalk:
    clientID: 
    clientSecret: 
    repository: 
    owner: 
    admin: 
  valine:
    app_id: 
    app_key: 
    placeholder: 
    visitor: 
    meta: 
pageview:
  provider: false
  leancloud:
    app_id: 
    app_key: 
    app_class: 
search:
  provider: default
  google:
    custom_search_engine_id: 
analytics:
  provider: google
  google:
    tracking_id: G-2EVZHSP7MW
    anonymize_ip: true
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
- CHANGELOG.md
- HOW_TO_RELEASE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- "/docs"
- "/node_modules"
- "/screenshots"
- "/test"
- "/vendor"
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji
